<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0bf72345-2382-4f1f-8157-b34ee1461fb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_widget_1727304118978']/section/div/div/div/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;AutomationTesting_Leader_Leader-2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;AutomationTesting_Leader_Leader-2&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a2380cc-5ccf-44a6-a05b-9dd24d951674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://katalon.com/hubfs/AutomationTesting_Leader_Leader-2.svg</value>
      <webElementGuid>47a09e03-58be-494f-9017-69e80fa63578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>AutomationTesting_Leader_Leader-2</value>
      <webElementGuid>58bca8c6-7cb0-405e-b391-1aaa9dbada26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_widget_1727304118978&quot;)/section[@class=&quot;hero-double-a__371 hero-double-a bg-white&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;hero-a--wrapper&quot;]/div[@class=&quot;hero-a__left--container  p-t-large p-b-large&quot;]/div[@class=&quot;buttons-a__container&quot;]/div[@class=&quot;buttons--icon-image&quot;]/img[1]</value>
      <webElementGuid>122476a2-69b3-4a5b-acc6-a55b9cd90636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_widget_1727304118978']/section/div/div/div/div/div/img</value>
      <webElementGuid>dc45bf86-456a-46a1-ab3c-d60faeca7cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='AutomationTesting_Leader_Leader-2']</value>
      <webElementGuid>21cecf4c-97d4-49de-adf8-c1d9a7782a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>e9fb507c-7a43-4ccd-871f-d125d2100674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://katalon.com/hubfs/AutomationTesting_Leader_Leader-2.svg' and @alt = 'AutomationTesting_Leader_Leader-2']</value>
      <webElementGuid>4c360299-6922-43ca-a694-2bd3543d6485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
